server:
    port: 8080

spring:
    cloud:
        gateway:
            routes:
                - id: first-component
                  uri: http://localhost:8081
                  predicates:
                    - Path=/api/v1/first

                - id: second-component
                  uri: http://localhost:8082
                  predicates:
                    - Path=/api/v1/second