server:
    port: 8080

spring:
    cloud:
        gateway:
            routes:
                - id: first-component-app
                  uri: ${FIRST_COMPONENT_URL}
                  predicates:
                    - Path=/api/v1/first

                - id: second-component-app
                  uri: ${SECOND_COMPONENT_URL}
                  predicates:
                    - Path=/api/v1/second