apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-component-app
  labels:
    app: first-component-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-component-app
  template:
    metadata:
      labels:
        app: first-component-app
    spec:
      containers:
      - name: first-component-app
        image: 09031995/first-component:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: first-component-svc
spec:
  selector:
    app: first-component-app
  ports:
  - port: 8081
    targetPort: 8081
