apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-component-app
  labels:
    app: gateway-component-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-component-app
  template:
    metadata:
      labels:
        app: gateway-component-app
    spec:
      containers:
      - name: gateway-component-app
        image: 09031995/gateway-component:latest
        resources: {}
        env:
          - name: FIRST_COMPONENT_URL
            value: http://first-component-svc:8081
          - name: SECOND_COMPONENT_URL
            value: http://second-component-svc:8082

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-component-svc
spec:
  selector:
    app: gateway-component-app
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080