apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-component-app
  labels:
    app: second-component-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-component-app
  template:
    metadata:
      labels:
        app: second-component-app
    spec:
      containers:
      - name: second-component-app
        image: 09031995/second-component:latest
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: second-component-svc
  labels:
    app: second-component-svc
spec:
  selector:
    app: second-component-app
  ports:
  - port: 8082
    targetPort: 8082
