apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-component-app
  labels:
    app: first-component-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-component-app
  template:
    metadata:
      labels:
        app: first-component-app
    spec:
      containers:
      - name: first-component-app
        image: 09031995/first-component:latest
        resources: {}
