apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-component-app
  labels:
    app: second-component-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-component-app
  template:
    metadata:
      labels:
        app: second-component-app
    spec:
      containers:
      - name: second-component-app
        image: 09031995/second-component:latest
        resources: {}